# Generated by Django 2.2.28 on 2023-11-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231106_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
    ]
